FROM python:alpine AS base

################################################### get app
FROM base AS app
ARG YT_USER=yotter
ARG YT_UID=1000
ARG YT_GID=1000
RUN addgroup -g ${YT_GID} yotter \
 && adduser -h /yotter -G yotter -D -u ${YT_UID} ${YT_USER}
COPY --chown=${YT_UID}:${YT_GID} . /yotter

################################################### get requirements
FROM base AS build
#gevent needs gcc, Brotli needs g++
RUN apk --no-cache add gcc musl-dev libffi-dev file make g++
RUN python -m pip install --upgrade pip

#COPY --from=app /yotter/requirements.txt /yotter/
#COPY --from=app /yotter/youtube-local/requirements.txt /yotter/youtube-local/
COPY requirements.txt /yotter/
COPY youtube-local/requirements.txt /yotter/ytl-requirements.txt

RUN pip install --no-cache-dir --prefix=/install -r /yotter/requirements.txt \
 && pip install --no-cache-dir --prefix=/install -r /yotter/ytl-requirements.txt


################################################### final image
FROM app AS instance
ARG YT_UID=1000
ARG YT_GID=1000

COPY --from=build /install /usr/local

COPY yotter-config.yaml /config/

ENV YOTTER_CONFIG_FILE=/config/yotter-config.yaml
ENV YOTTER_SQLITE_DB_FILE=/config/yotter.db
ENV YOTTER_TEMP_DIR=/tmp
ENV YOTTER_CACHE_DIR=/tmp/yotter-cache

WORKDIR /yotter
USER ${YT_UID}:${YT_GID}
CMD cd /yotter \
 && flask db upgrade \
 && gunicorn -b 0.0.0.0:5000 -w 4 yotter:app

EXPOSE 5000
