
serverName: "yotter.xyz"
nitterInstance: "https://nitter.net/"
maxInstanceUsers: 100
serverLocation: "Germany"
restrictPublicUsage: true
nginxVideoStream: true
maintenance_mode: false
show_admin_message: false
admin_message_title: "Message from the admin"
admin_message: "Message from the admin text"
admin_user: "admin_username"
max_old_user_days: 60
donate_url: ""

