
server_name: "yotter.xyz"

# set to 0 to disable new registrations
max_instance_users: 100

# eg "Germany"
server_location: "?"

# Deprecated
#restrictPublicUsage: true

# Deprecated
#nginxVideoStream: true

# Whether to proxy images (thumbnails etc.) through the server
proxy_images: true

# Whether to proxy video (or audio) streams through the server
proxy_videos: true

# Url for external proxy server
# If this is unset and `proxy_*` is set to true, requests will be proxied internally.
# It's recommended to use an external proxy such as nginx for better performance.
#
# It's possible to use variables in `{}` that refer to the original request url:
# `scheme`, `netloc` (host:port), `path` (with a leading `/`), `query` (without leading `?`), `fragment` (without leading `#`): as per `urllib.parse.urlparse`
# `scheme_encoded`, `netloc_encoded` etc.: same as above but urlencoded
# `url`, `url_encoded`: the original request url, and urlencoded variant
#
# The example below works for the nginx configuration in `SELF-HOSTING.md`
#
#external_proxy: "https://my.nginx.instance{path}?{query}&host={netloc}"

# When true, also disables user registration
maintenance_mode: false
show_admin_message: false
admin_message_title: "Message from the admin"
admin_message: "Message from the admin text"
admin_user: "admin_username"
max_old_user_days: 60
donate_url: ""

# Allow anonymous users. Note that anonymous users are restricted wrt restricted_mode.
require_login: true

# When true, restricted users will only be able to watch a selection of channels/playlists curated by the admin user.
restricted_mode: false