"""timestamps

Revision ID: 6a0abbea9058
Revises: 8f67c3a6c5a1
Create Date: 2020-10-31 10:36:15.000983

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6a0abbea9058'
down_revision = '8f67c3a6c5a1'
branch_labels = None
depends_on = None

from datetime import datetime
now = datetime.strftime(datetime.utcnow(), '%Y-%m-%d %H:%M:%S')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channel_assoc', sa.Column('created_on', sa.DateTime(), nullable=False, server_default=sa.sql.quoted_name(now, True)))
    op.add_column('user_playlist_assoc', sa.Column('created_on', sa.DateTime(), nullable=False, server_default=sa.sql.quoted_name(now, True)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_playlist_assoc', 'created_on')
    op.drop_column('user_channel_assoc', 'created_on')
    # ### end Alembic commands ###
