"""initial

Revision ID: 8f67c3a6c5a1
Revises: 
Create Date: 2020-10-30 10:16:41.887531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f67c3a6c5a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('yt_channel',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_index(op.f('ix_yt_channel_id'), 'yt_channel', ['id'], unique=True)
    op.create_index(op.f('ix_yt_channel_is_allowed'), 'yt_channel', ['is_allowed'], unique=False)
    op.create_index(op.f('ix_yt_channel_is_blocked'), 'yt_channel', ['is_blocked'], unique=False)
    op.create_table('yt_playlist',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_index(op.f('ix_yt_playlist_id'), 'yt_playlist', ['id'], unique=True)
    op.create_index(op.f('ix_yt_playlist_is_allowed'), 'yt_playlist', ['is_allowed'], unique=False)
    op.create_table('yt_video',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_index(op.f('ix_yt_video_id'), 'yt_video', ['id'], unique=True)
    op.create_table('user_channel_assoc',
    sa.Column('channel_rowid', sa.Integer(), nullable=True),
    sa.Column('user_rowid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_rowid'], ['yt_channel.rowid'], ),
    sa.ForeignKeyConstraint(['user_rowid'], ['user.rowid'], )
    )
    op.create_table('user_playlist_assoc',
    sa.Column('playlist_rowid', sa.Integer(), nullable=True),
    sa.Column('user_rowid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_rowid'], ['yt_playlist.rowid'], ),
    sa.ForeignKeyConstraint(['user_rowid'], ['user.rowid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_playlist_assoc')
    op.drop_table('user_channel_assoc')
    op.drop_index(op.f('ix_yt_video_id'), table_name='yt_video')
    op.drop_table('yt_video')
    op.drop_index(op.f('ix_yt_playlist_is_allowed'), table_name='yt_playlist')
    op.drop_index(op.f('ix_yt_playlist_id'), table_name='yt_playlist')
    op.drop_table('yt_playlist')
    op.drop_index(op.f('ix_yt_channel_is_blocked'), table_name='yt_channel')
    op.drop_index(op.f('ix_yt_channel_is_allowed'), table_name='yt_channel')
    op.drop_index(op.f('ix_yt_channel_id'), table_name='yt_channel')
    op.drop_table('yt_channel')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
